services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000

  frontend:
    build:
      context: ./src/View/nature-help
      dockerfile: Dockerfile
    ports:
      - "5051:80"
    depends_on:
      - backend
