services:
  postgres:
    profiles:
      - with-postgres

  backend:
    environment:
      ConnectionStrings__LocalConnection: "Host=localhost;Port=5432;Database=NatureHelpDB;Username=postgres;Password=10101010;Trust Server Certificate=true;Timeout=30;Command Timeout=30"
    depends_on:
      redis:
        condition: service_healthy
