server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location = / {
        return 301 /nature-help/;
    }

    location /nature-help/ {
        alias /usr/share/nginx/html/nature-help/;
        try_files $uri $uri/ /nature-help/index.html;
    }
}