name: Run .NET and Cypress Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/NatureHelp

      - name: Build project
        run: dotnet build --no-restore
        working-directory: ./src/NatureHelp

      - name: Run xUnit tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ./src/NatureHelp

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM dependencies
        run: npm ci
        working-directory: ./src/View/nature-help

      - name: Run Cypress Component Tests
        run: npm run cy:component
        working-directory: ./src/View/nature-help

      # Start ASP.NET Core backend
      - name: Start ASP.NET Core App
        run: |
          nohup dotnet run --project ./src/NatureHelp/NatureHelp.csproj > server.log 2>&1 &
          echo "⏳ ASP.NET Core app starting..."
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: http://localhost:7077
          ConnectionStrings__DefaultConnection: Host=localhost;Database=testdb;Username=postgres;Password=postgres;

      - name: Wait for backend
        run: |
          npx wait-on http://localhost:7077 --timeout 60000

      - name: Check logs
        run: cat server.log

      - name: Run Cypress E2E Tests
        run: npm run cy:e2e
        working-directory: ./src/View/nature-help
