name: Run .NET and Cypress Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Run xUnit tests
        run: dotnet test --no-build --verbosity normal

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM dependencies
        run: npm ci
        working-directory: ./src/View/nature-help

      - name: Run Cypress Component Tests
        run: npm run cy:component
        working-directory: ./src/View/nature-help

      # Start ASP.NET Core backend
      - name: Start ASP.NET app
        run: |
          dotnet run --project ./src/NatureHelp/NatureHelp.csproj
          echo "✅ ASP.NET Core app started"
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ConnectionStrings__DefaultConnection: Host=localhost;Database=testdb;Username=postgres;Password=postgres;

      - name: Wait for API to be ready
        run: npx wait-on --race http://localhost:7077 http://localhost:5242 --timeout 60000
        
      - name: Run Cypress E2E Tests
        run: npm run cy:e2e
        working-directory: ./src/View/nature-help
