name: Cypress E2E Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM dependencies
        run: npm ci
        working-directory: ./src/View/nature-help

      - name: Restore backend
        run: dotnet restore
        working-directory: ./src/NatureHelp

      - name: Start ASP.NET Core App
        run: |
          nohup dotnet run --project ./src/NatureHelp/NatureHelp.csproj > server.log 2>&1 &
          echo "⏳ ASP.NET Core app starting..."
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: https://0.0.0.0:5000
          ConnectionStrings__DefaultConnection: Host=localhost;Database=testdb;Username=postgres;Password=postgres;

      - name: Wait for backend
        run: |
          npx wait-on http://localhost:7077 --timeout 60000 || (echo "Backend did not start in time" && cat server.log && exit 1)

      - name: Check logs
        run: cat server.log

      - name: Run Cypress E2E Tests
        run: npm run cy:e2e
        working-directory: ./src/View/nature-help
